# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:16.13.0

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# cache:
#   paths:
#   - node_modules/

before_script:
  - yarn install --registry http://172.16.11.21:4873

stages:
  - lint
  - test
  - publish

lint:
  stage: lint
  script:
   - npx sucrase-node scripts/gen-version.ts
   - npx eslint . --ext .vue,.js,.ts,.jsx,.tsx --max-warnings 0 --fix
  only:
   - /^(feature-)/
   - /^(release-)/
   - /^(fix-)/
   - dev

# 发布开发环境应用
pub-test:
  stage: test
  script:
   - npx sucrase-node scripts/gen-version.ts
   - yarn build-app
   - node ./node_modules/pubt/bin/pubt.js commit -f app/dist/iScene -d http://172.16.11.19:4899/receiver -t D:\\tomcat-8010\\webapps\\web3d-next\\iScene -r
   - yarn build-docs
   - node ./node_modules/pubt/bin/pubt.js commit -f document/dist -d http://172.16.11.19:4899/receiver -t D:\\tomcat-8010\\webapps\\smart3d-vue\\ -r
  only:
    - dev

# 发布版本
publish:
  stage: publish
  variables:
    TAG_VERSION: $CI_COMMIT_TAG
    SSH_USERNAME: $SSH_USERNAME
    SSH_PASSWORD: $SSH_PASSWORD
  script:
    - npx sucrase-node scripts/update-version.ts
    - npx sucrase-node scripts/gen-version.ts
    - yarn build-lib
    - yarn build-docs
    - node ./scripts/pub-document.js
    - npx sucrase-node scripts/pre-publish.ts
    - npm config set //172.16.11.21:4873/:_authToken $NPM_AUTH_TOKEN
    - npm publish --registry http://172.16.11.21:4873 --access public
  only:
    - tags
