// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ReportingContent: typeof import('./src/components/ReportingContent.vue')['default']
    ReportingHeader: typeof import('./src/components/ReportingHeader.vue')['default']
    ReportingWrapper: typeof import('./src/components/ReportingWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartMenu: typeof import('./src/components/smart-menu/SmartMenu.vue')['default']
    SmartsTabsItem: typeof import('./src/components/smartTabs/SmartsTabsItem.vue')['default']
    SmartTabs: typeof import('./src/components/smartTabs/SmartTabs.vue')['default']
    WorkBench: typeof import('./src/components/WorkBench.vue')['default']
    WorkBenchLeft: typeof import('./src/components/WorkBenchLeft.vue')['default']
  }
}

export {}
